config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # get "yachts", to: "yachts#index"
  # Defines the root path route ("/")
  # root "articles#index"
  resources :yachts do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index, :show, :edit, :update, :destroy] do
    # get "show", to: "bookings#show", as: :show
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :yacht
  belongs_to :user

  validates :start_date, :end_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :yachts
  has_many :bookings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/yacht.rb
class Yacht < ApplicationRecord
  has_many :bookings, dependent: :destroy
  belongs_to :user
  has_many_attached :photos
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  validates :name, :description, :location, :price_per_day, :length, :capacity, :cabin, :crew, presence: true
  validates :description, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_yacht, only: [:new, :create]

  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.yacht = @yacht
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @booking = Booking.find(params[:id])
    @yacht = @booking.yacht
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to booking_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path, status: :see_other
  end

  private

  def find_yacht
    @yacht = Yacht.find(params[:yacht_id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/yachts_controller.rb
class YachtsController < ApplicationController
  before_action :find_yacht, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @query = params[:query]
      @yachts = Yacht.where("name LIKE ?", "%#{params[:query]}%")
    else
      @yachts = Yacht.all
    end

    @markers = @yachts.geocoded.map do |yacht|
      {
        lat: yacht.latitude,
        lng: yacht.longitude
      }
    end
  end

  def show
    @booking = Booking.new
    # We want our map in the show page not index page like in lecture notes
    # In our case we only show marker for 1 yacht, so no need to loop through array.
    # However, JS map_controller expects an array to be passed in, so we make @marker an array
    @marker = [{
      lat: @yacht.latitude,
      lng: @yacht.longitude,
      info_window: render_to_string(partial: "info_window", locals: { yacht: @yacht })
    }]
  end

  def new
    @yacht = Yacht.new
  end

  def create
    @yacht = Yacht.new(yacht_params)
    @yacht.user = current_user
    if @yacht.save
      redirect_to yachts_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    # This is the array of photos that I want to upload
    # array = params[:yacht][:photos]
    # Here we update all of the other info for a yacht - excluding photos
    if @yacht.update(yacht_params)
      # The first element of the array is an empty string - something to do with active storage
      # We delete the empty string
      # array.delete_at(0)
      # What remains are the other photos. We loop through them and attach them to existing photos
      # Following the convention that active storage expects
      # :photos <<
      # array.each { |photo| @yacht.photos.attach(io: photo.tempfile, filename: "test", content_type: "image/png") }
      @yacht.save
      redirect_to yacht_path(@yacht)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @yacht.destroy
    redirect_to yachts_path, status: :see_other
  end

  private

  def yacht_params
    params.require(:yacht).permit(:name,
                                  :length,
                                  :capacity,
                                  :description,
                                  :crew,
                                  :price_per_day,
                                  :location,
                                  :cabin,
                                  :speed,
                                  photos: [])
  end

  def find_yacht
    @yacht = Yacht.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Change your booking of <%= @yacht.name %> yacht</h3>
        <%= simple_form_for @booking do |f| %>
          <%= f.input :start_date, placeholder: "Enter a start_date" %>
          <%= f.input :end_date, placeholder: "Enter a end_date" %>
          <%= f.submit "Change a booking", class: "btn btn-flat" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<br>
<br>

<h1>My Bookings</h1>
<div class="container">
  <div class="row">
    <ul>
      <% current_user.bookings.each do |booking| %>
        <div class="card-booking">
          <div class="booking-components">
            <div class="booking-image" style="background-image: url('<%= booking.yacht.photos.attached? ? "#{cl_image_path booking.yacht.photos.first.key}" : "https://images.theconversation.com/files/403129/original/file-20210527-21-wxxnze.jpg" %>');">
            </div>
            <div class="booking-details">
              <div class="info">
                <h2><%= link_to "#{booking.yacht.name}", booking_path(booking) %></h2>
                <div class="info-detail">
                  <div class="short-desc">
                    <p>Start date: <%= booking.start_date %></p>
                    <p>End date: <%= booking.end_date %></p>
                  </div>
                </div>
              </div>
              <div class="action-buttons">
                <div class="button">
                  <%= link_to "Edit", edit_booking_path(booking) %>
                </div>
                <div class="button">
                  <%= link_to "Delete",
                      booking_path(booking),
                      data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </ul>
  </div>
</div>

<%# link_to "#{@booking.yacht.name}", booking_path(booking) %>

app/views/bookings/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Book <%= @yacht.name %> yacht 🙋</h3>
        <%= simple_form_for [@yacht, @booking] do |f| %>
          <%= f.input :start_date, placeholder: "Enter a start_date" %>
          <%= f.input :end_date, placeholder: "Enter a end_date" %>
          <%= f.submit "Create a booking", class: "btn btn-flat" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<br>
<br>

<h1><strong>Booking Confirmation<strong></h1>
<div class="container">
  <div class="row">
    <ul>
        <div class="card-booking-new">
          <div class="booking-components">
            <% if @booking.yacht.photos.attached? %>
              <%= cl_image_tag @booking.yacht.photos.first.key, width: 300; %>
            <% else %>
              <%= image_tag("https://images.theconversation.com/files/403129/original/file-20210527-21-wxxnze.jpg?ixlib=rb-1.1.0&rect=0%2C0%2C4537%2C3022&q=45&auto=format&w=926&fit=clip", width: 250) %>
            <% end %>
            <div class="booking-details">
              <div class="info">
                <h2><%= link_to @booking.yacht.name, yacht_path(@booking.yacht) %></h2>
                <div class="info-detail">
                  <div class="short-desc">
                    <p>Start date: <%= @booking.start_date %></p>
                    <p>End date: <%= @booking.end_date %></p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
    </ul>
  </div>
</div>

<br>

<div class="links">

  <%= link_to "See All My Bookings", bookings_path %>

  <%= link_to "Change This Booking", edit_booking_path(@booking) %>

  <%= link_to "Delete This Booking", booking_path(@booking),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Atlantis</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300&display=swap" rel="stylesheet">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body>
    <br>
    <br>
    <br>
    <br>
    <p class="alert"><%= alert %></p>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner-video">
  <div class="video-tint">
  </div>
  <%= video_tag "water.mp4", autoplay: :autoplay, loop: :loop, muted: :muted, class: "home_video" %>
  <div class="text">
    <h1><strong>Luxury Yachts for Charter<strong></h1>
    <p>We are proven yacht charter experts in the Mediterranean, Caribbean and across the globe
        with a large selection of sailing and motor yachts for rent.
    </p>
  </div>
</div>

<div class="cta">
  <h1><strong>Book your Super Yacht vacation with us<strong></h1>
  <br>
  <p>For over 25 years <strong>Atlantis<strong> has been providing the ultimate in yacht charter for both corporate entertainment and private vacations. We ensure your yacht charter will be a success.</p>
</div>

<br>

<div class="discover">
  <%= link_to yachts_path do %>
    <div class="text">
      <h2>Discover our <strong>Yachts<strong> Selection</h2>
      <%# <p>Make your next vacation the one to remember</p> %>
    </div>
    <div class="img-tint"></div>
    <%= image_tag("harbor.png") %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark navbar-lewagon sticky">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "ATLANTIS.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Discover", "/yachts", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://pyxis.nymag.com/v1/imgs/dec/970/81245a2b4368ace8e61988cedea6a204d6-30-Elon-Musk.rsquare.w700.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "Add My Yacht", "/yachts/new", class: "dropdown-item" %>
              <%= link_to "Log Out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/yachts/_info_window.html.erb
<h2><%= yacht.name %></h2>
<p><%= yacht.location %></p>

app/views/yachts/edit.html.erb
<div class="container pt-6">
  <div class="row justify-content-center">
    <h2 class="text-center mb-4" style="font-family: Inter, sans-serif">Update Yacht Details</h2>
    <div class="card p-3 shadow-lg col-lg-8 col-md-8 col-sm-12">
      <%= simple_form_for @yacht do |f| %>
        <%= f.input :name %>
        <%= f.input :length %>
        <%= f.input :capacity %>
        <%= f.input :description %>
        <%= f.input :crew %>
        <%= f.input :price_per_day %>
        <%= f.input :location %>
        <%= f.input :cabin %>
        <%= f.input :speed %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.submit "Update My Yacht", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/yachts/index.html.erb
<div class="container">
  <div class="map map-index" style="width: 100%; height: 300px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  <div class="row">
    <% @yachts.each do |yacht| %>
    <div class="spacing col-lg-6 col-md-12 col-sm-12">
      <%= link_to yacht_path(yacht) do %>
      <div class="card">
        <% if yacht.photos.attached? %>
          <%= cl_image_tag yacht.photos.first.key %>
        <% else %>
          <img src="https://images.theconversation.com/files/403129/original/file-20210527-21-wxxnze.jpg?ixlib=rb-1.1.0&rect=0%2C0%2C4537%2C3022&q=45&auto=format&w=926&fit=clip" />
        <% end %>
        <div class="card-infos">
          <div>
            <h2><%= yacht.name %></h2>
            <div class="short-desc index-page">
              <p>Length: <%= yacht.length %> |</p>
              <p>Capacity: <%= yacht.capacity %> |</p>
              <p>Cabins: <%= yacht.cabin %> |</p>
              <p>Location: <%= yacht.location %></p>
            </div>
          </div>
        </div>
        </div>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/yachts/new.html.erb
<div class="container pt-6">
  <div class="row justify-content-center">
    <h2 class="text-center mb-4" style="font-family: Inter, sans-serif">My Yacht Details</h2>
    <div class="card p-3 shadow-lg col-lg-8 col-md-8 col-sm-12">
      <%= simple_form_for @yacht do |f| %>
        <%= f.input :name %>
        <%= f.input :length %>
        <%= f.input :capacity %>
        <%= f.input :description %>
        <%= f.input :crew %>
        <%= f.input :price_per_day %>
        <%= f.input :location %>
        <%= f.input :cabin %>
        <%= f.input :speed %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.submit "Add My Yacht", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/yachts/show.html.erb
<div class="front-img">
  <% if @yacht.photos.attached? %>
   <%= cl_image_tag @yacht.photos.first.key %>
  <% else %>
    <%= image_tag("https://images.theconversation.com/files/403129/original/file-20210527-21-wxxnze.jpg?ixlib=rb-1.1.0&rect=0%2C0%2C4537%2C3022&q=45&auto=format&w=926&fit=clip") %>
  <% end %>
</div>

<br>

<h1><strong><%= @yacht.name %><strong></h1>

<div class="description">
  <p><%= @yacht.description %></p>
</div>

<br>

<div class="features">
  <div class="feature">
    <i class="fa-solid fa-ruler"></i>
    <p>Length: <%= @yacht.length %> m</p>
  </div>
  <div class="feature">
    <i class="fa-solid fa-person"></i>
    <p>Capacity: <%= @yacht.capacity %></p>
  </div>
  <div class="feature">
    <i class="fa-solid fa-person-booth"></i>
    <p>Cabins: <%= @yacht.cabin %></p>
  </div>
  <div class="feature">
    <i class="fa-solid fa-anchor"></i>
    <p>Crew: <%= @yacht.crew %></p>
  </div>
  <div class="feature">
    <i class="fa-solid fa-gauge-high"></i>
    <p>Speed: <%= @yacht.speed %> knots</p>
  </div>
  <div class="feature">
    <i class="fa-solid fa-hand-holding-dollar"></i>
    <p>Price/day £<%= @yacht.price_per_day %></p>
  </div>

  <div class="feature">
    <i class="fa-solid fa-location-dot"></i>
    <p>Location: <%= @yacht.location %></p>
  </div>
</div>

<br>

<div class="container">
  <div class="row">
    <% @yacht.photos.each do |photo| %>
      <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="shadow-img", style="background-image: url('<%= cl_image_path photo.key %>');">
          <%# <%= cl_image_tag photo.key, width: 300 %> 
        </div>
      </div>
    <% end %>
  </div>
</div>


<br>

<div class="map">
  <h2>Current Location:<strong> <%= @yacht.location %><strong></h2>
  <div class="map-card">
    <div style="width: 100%; height: 300px;"
      data-controller="map"
      <%# We need to pass @marker here instead of @markers in the lecture notes %>
      data-map-markers-value="<%= @marker.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

<br>

<% if current_user != @yacht.user %>
  <div class="booking">
    <h2><strong>Book <%= @yacht.name %><strong></h2>
    <div class="booking-card">
      <%= simple_form_for [@yacht, @booking] do |f| %>
        <%= f.input :start_date, as: :date, html5: true %>
        <%= f.input :end_date, as: :date, html5: true %>
        <br>
        <div class="button-wrapper">
          <%= f.submit "Book", class: "book-button" %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<br>

<div class="container mb-5">
  <div class="actions">
    <div class="button">
      <%= link_to "Back", yachts_path %>
    </div>
    <% if current_user == @yacht.user %>
      <div class="button">
        <%= link_to "Edit Yacht",
          edit_yacht_path(@yacht) %>
      </div>
      <div class="button">
        <%= link_to "Delete Yacht",
          yacht_path(@yacht),
          data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
        %>
      </div>
    <% end %>
  </div>
</div>